### PR TITLE
F3-2084: Update USB cam param name

### PR DESCRIPTION
**Pull request by hjoe72**
Update USB cameras param name.

### CODE REVIEW

**Review by zzv2 — COMMENTED** [review]
does this make it incompatible with the old cameras?

**Comment by hjoe72** [comment]
> does this make it incompatible with the old cameras?

Actually nevermind, this seems more related with the v4l2 version installed rather than camera specific. So I'm closing this for now since this is what works for Flippy

**Review by dtamino — APPROVED** [review]
So, new v4l2 driver versions changed the names of the parameters, or why the change?

**Comment by hjoe72** [comment]
> So, new v4l2 driver versions changed the names of the parameters, or why the change?

yes, it's the driver version

**Review by zzv2 — APPROVED** [review]

**Pull request merged**
